/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2017-11-02 03:33:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005ftopic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>发表问题 编辑问题 公用</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/css/global.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"/\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"index.html\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-user\">      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      \r\n");
      out.write("      <a class=\"avatar\" href=\"../user/index.html\">\r\n");
      out.write("        <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\">\r\n");
      out.write("        <cite>贤心</cite>\r\n");
      out.write("        <i>VIP2</i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"nav\">\r\n");
      out.write("        <a href=\"../user/set.html\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
      out.write("        <a href=\"\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main layui-clear\">\r\n");
      out.write("  <div class=\"fly-panel\" pad20>\r\n");
      out.write("    <h2 class=\"page-title\">发表问题</h2>\r\n");
      out.write("    \r\n");
      out.write("    <!-- <div class=\"fly-none\">并无权限</div> -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"layui-form layui-form-pane\">\r\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/save_topic.do\" method=\"post\">\r\n");
      out.write("        <div class=\"layui-form-item\">\r\n");
      out.write("          <label for=\"L_title\" class=\"layui-form-label\">标题</label>\r\n");
      out.write("          <div class=\"layui-input-block\">\r\n");
      out.write("            <input type=\"text\" id=\"L_title\" name=\"title\" required lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"layui-form-item layui-form-text\">\r\n");
      out.write("          <div class=\"layui-input-block\">\r\n");
      out.write("            <textarea id=\"L_content\" name=\"content\" required lay-verify=\"required\" placeholder=\"请输入内容\" class=\"layui-textarea fly-editor\" style=\"height: 260px;\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          <label for=\"L_content\" class=\"layui-form-label\" style=\"top: -2px;\">描述</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"layui-form-item\">\r\n");
      out.write("          <div class=\"layui-inline\">\r\n");
      out.write("            <label class=\"layui-form-label\">所在类别</label>\r\n");
      out.write("            <div class=\"layui-input-block\">\r\n");
      out.write("              <select lay-verify=\"required\" name=\"class\">\r\n");
      out.write("                <option></option>\r\n");
      out.write("                <option value=\"1\" >layui框架综合</option> \r\n");
      out.write("                <option value=\"2\" >layui.mobile模块</option> \r\n");
      out.write("                <option value=\"3\" >layer弹出层</option> \r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-inline\">\r\n");
      out.write("            <label class=\"layui-form-label\">悬赏飞吻</label>\r\n");
      out.write("            <div class=\"layui-input-block\">\r\n");
      out.write("              <select name=\"experience\">\r\n");
      out.write("                <option value=\"5\" selected>5</option>\r\n");
      out.write("                <option value=\"20\">20</option>\r\n");
      out.write("                <option value=\"50\">50</option>\r\n");
      out.write("                <option value=\"100\">100</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<!--         <div class=\"layui-form-item\">\r\n");
      out.write("          <label for=\"L_vercode\" class=\"layui-form-label\">人类验证</label>\r\n");
      out.write("          <div class=\"layui-input-inline\">\r\n");
      out.write("            <input type=\"text\" id=\"L_vercode\" name=\"vercode\" required lay-verify=\"required\" placeholder=\"请回答后面的问题\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-mid\">\r\n");
      out.write("            <span style=\"color: #c00;\">1+1=?</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <div class=\"layui-form-item\">\r\n");
      out.write("          <button class=\"layui-btn\" lay-filter=\"*\" lay-submit>立即发布</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'jie';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
