/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2017-11-07 02:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Fly Template v2.0，基于 layui 的轻量级社区模版</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/css/global.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"/\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"index.html\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-user\">\r\n");
      out.write("      <!-- 未登入状态 -->\r\n");
      out.write("      <a class=\"unlogin\" href=\"user/login.html\"><i class=\"iconfont icon-touxiang\"></i></a>\r\n");
      out.write("      <span><a href=\"user/login.html\">登入</a><a href=\"user/reg.html\">注册</a></span>\r\n");
      out.write("      <p class=\"out-login\">\r\n");
      out.write("        <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-qq\" title=\"QQ登入\"></a>\r\n");
      out.write("        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-weibo\" title=\"微博登入\"></a>\r\n");
      out.write("      </p>   \r\n");
      out.write("      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      <!-- \r\n");
      out.write("      <a class=\"avatar\" href=\"user/index.html\">\r\n");
      out.write("        <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\">\r\n");
      out.write("        <cite>贤心</cite>\r\n");
      out.write("        <i>VIP2</i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"nav\">\r\n");
      out.write("        <a href=\"/user/set/\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
      out.write("        <a href=\"/user/logout/\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
      out.write("      </div> -->\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main layui-clear\">\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("    <div class=\"content detail\">\r\n");
      out.write("      <div class=\"fly-panel detail-box\">\r\n");
      out.write("        <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h1>\r\n");
      out.write("        <div class=\"fly-tip fly-detail-hint\" data-id=\"{{rows.id}}\">\r\n");
      out.write("          <span class=\"fly-tip-stick\">置顶帖</span>\r\n");
      out.write("          <span class=\"fly-tip-jing\">精帖</span>\r\n");
      out.write("          \r\n");
      out.write("          <span>未结贴</span>\r\n");
      out.write("          <!-- <span class=\"fly-tip-jie\">已采纳</span> -->\r\n");
      out.write("          \r\n");
      out.write("          <!-- <span class=\"jie-admin\" type=\"del\" style=\"margin-left: 20px;\">删除</span>\r\n");
      out.write("          <span class=\"jie-admin\" type=\"set\" field=\"stick\" rank=\"1\">置顶</span> \r\n");
      out.write("          <span class=\"jie-admin\" type=\"set\" field=\"stick\" rank=\"0\" style=\"background-color:#ccc;\">取消置顶</span>\r\n");
      out.write("          <span class=\"jie-admin\" type=\"set\" field=\"status\" rank=\"1\">加精</span> \r\n");
      out.write("          <span class=\"jie-admin\" type=\"set\" field=\"status\" rank=\"0\" style=\"background-color:#ccc;\">取消加精</span> -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"fly-list-hint\"> \r\n");
      out.write("            <i class=\"iconfont\" title=\"回答\">&#xe60c;</i> 517\r\n");
      out.write("            <i class=\"iconfont\" title=\"人气\">&#xe60b;</i>  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.viewCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"detail-about\">\r\n");
      out.write("          <a class=\"jie-user\" href=\"\">\r\n");
      out.write("            <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\" alt=\"\">\r\n");
      out.write("            <cite>\r\n");
      out.write("              ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("              <em> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.createtime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</em>\r\n");
      out.write("            </cite>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"detail-hits\" data-id=\"{{rows.id}}\">\r\n");
      out.write("            <span style=\"color:#FF7200\">悬赏：20飞吻</span>\r\n");
      out.write("            <span class=\"layui-btn layui-btn-mini jie-admin\" type=\"edit\"><a href=\"/jie/edit/{{rows.id}}\">编辑此贴</a></span>\r\n");
      out.write("            <span class=\"layui-btn layui-btn-mini jie-admin \" type=\"collect\" data-type=\"add\">收藏</span>\r\n");
      out.write("            <!--<span class=\"layui-btn layui-btn-mini jie-admin  layui-btn-danger\" type=\"collect\" data-type=\"add\">取消收藏</span>-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"text\">\r\n");
      out.write("        <div class=\"detail-body photos\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("          ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"fly-panel detail-box\" style=\"padding-top: 0;\">\r\n");
      out.write("        <a name=\"comment\"></a>\r\n");
      out.write("        <ul class=\"jieda photos\" id=\"jieda\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("          <!-- <li class=\"fly-none\">没有任何回答</li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"layui-form layui-form-pane\">\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/submit_comment.do\" method=\"post\">\r\n");
      out.write("            <div class=\"layui-form-item layui-form-text\">\r\n");
      out.write("              <div class=\"layui-input-block\">\r\n");
      out.write("                <textarea id=\"L_content\" name=\"content\" required lay-verify=\"required\" placeholder=\"我要回答\"  class=\"layui-textarea fly-editor\" style=\"height: 150px;\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <input type=\"hidden\" name=\"topic_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              <input type=\"hidden\" name=\"jid\" value=\"{{rows.id}}\">\r\n");
      out.write("              <input type=\"submit\" class=\"layui-btn\" lay-filter=\"*\" value=\"提交回答\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"edge\">\r\n");
      out.write("    <dl class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt class=\"fly-panel-title\">最近热帖</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局（基本结构）</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 6087</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">Java实现LayIM后端的核心代码</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 767</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局（基本结构）</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 6087</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">Java实现LayIM后端的核心代码</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 767</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局（基本结构）</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 6087</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">Java实现LayIM后端的核心代码</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 767</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局（基本结构）</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 6087</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">Java实现LayIM后端的核心代码</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60b;</i> 767</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("    \r\n");
      out.write("    <dl class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt class=\"fly-panel-title\">近期热议</dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("      <dd>\r\n");
      out.write("        <a href=\"\">使用 layui 秒搭后台大布局之基本结构</a>\r\n");
      out.write("        <span><i class=\"iconfont\">&#xe60c;</i> 96</span>\r\n");
      out.write("      </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'jie';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly', function(){\r\n");
      out.write("  var fly = layui.fly;\r\n");
      out.write("  //如果你是采用模版自带的编辑器，你需要开启以下语句来解析。\r\n");
      out.write("  /*\r\n");
      out.write("  $('.detail-body').each(function(){\r\n");
      out.write("    var othis = $(this), html = othis.html();\r\n");
      out.write("    othis.html(fly.content(html));\r\n");
      out.write("  });\r\n");
      out.write("  */\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /jsp/detail.jsp(106,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/detail.jsp(106,8) '${comments}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${comments}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /jsp/detail.jsp(106,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("comment");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <li data-id=\"12\" class=\"jieda-daan\">\r\n");
          out.write("            <a name=\"item-121212121212\"></a>\r\n");
          out.write("            <div class=\"detail-about detail-about-reply\">\r\n");
          out.write("              <a class=\"jie-user\" href=\"\">\r\n");
          out.write("                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/res/images/avatar/default.png\" alt=\"\">\r\n");
          out.write("                <cite>\r\n");
          out.write("                  <i>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</i>\r\n");
          out.write("                  <!-- <em>(楼主)</em>\r\n");
          out.write("                  <em style=\"color:#5FB878\">(管理员)</em>\r\n");
          out.write("                  <em style=\"color:#FF9E3F\">（活雷锋）</em>\r\n");
          out.write("                  <em style=\"color:#999\">（该号已被封）</em> -->\r\n");
          out.write("                </cite>\r\n");
          out.write("              </a>\r\n");
          out.write("              <div class=\"detail-hits\">\r\n");
          out.write("                <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("              </div>\r\n");
          out.write("              <i class=\"iconfont icon-caina\" title=\"最佳答案\"></i>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div class=\"detail-body jieda-body\">\r\n");
          out.write("              <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div class=\"jieda-reply\">\r\n");
          out.write("              <span class=\"jieda-zan zanok\" type=\"zan\"><i class=\"iconfont icon-zan\"></i><em>12</em></span>\r\n");
          out.write("              <span type=\"reply\"><i class=\"iconfont icon-svgmoban53\"></i>回复</span>\r\n");
          out.write("              <!-- <div class=\"jieda-admin\">\r\n");
          out.write("                <span type=\"edit\">编辑</span>\r\n");
          out.write("                <span type=\"del\">删除</span>\r\n");
          out.write("                <span class=\"jieda-accept\" type=\"accept\">采纳</span>\r\n");
          out.write("              </div> -->\r\n");
          out.write("            </div>\r\n");
          out.write("          </li>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
