/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2017-11-08 01:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>基于Layui的轻量级问答社区页面模版</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/css/global.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/js/template.js\" ></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"/\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"index.html\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-user\">\r\n");
      out.write("      <!-- 未登入状态 -->\r\n");
      out.write("      <a class=\"unlogin\" href=\"user/login.html\"><i class=\"iconfont icon-touxiang\"></i></a>\r\n");
      out.write("      <span><a href=\"user/login.html\">登入</a><a href=\"user/reg.html\">注册</a></span>\r\n");
      out.write("      <p class=\"out-login\">\r\n");
      out.write("        <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-qq\" title=\"QQ登入\"></a>\r\n");
      out.write("        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-weibo\" title=\"微博登入\"></a>\r\n");
      out.write("      </p>   \r\n");
      out.write("      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      <!-- \r\n");
      out.write("      <a class=\"avatar\" href=\"user/index.html\">\r\n");
      out.write("        <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\">\r\n");
      out.write("        <cite>贤心</cite>\r\n");
      out.write("        <i>VIP2</i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"nav\">\r\n");
      out.write("        <a href=\"/user/set/\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
      out.write("        <a href=\"/user/logout/\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
      out.write("      </div> -->\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main layui-clear\">\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("    <div class=\"content\" style=\"margin-right:0\">\r\n");
      out.write("      <div class=\"fly-tab\">\r\n");
      out.write("        <span>\r\n");
      out.write("          <a href=\"\" class=\"tab-this\">全部</a>\r\n");
      out.write("          <a href=\"\">未结帖</a>\r\n");
      out.write("          <a href=\"\">已采纳</a>\r\n");
      out.write("          <a href=\"\">精帖</a>\r\n");
      out.write("          <a href=\"../user/index.html\">我的帖</a>\r\n");
      out.write("        </span>\r\n");
      out.write("        <form action=\"http://cn.bing.com/search\" class=\"fly-search\">\r\n");
      out.write("          <i class=\"iconfont icon-sousuo\"></i>\r\n");
      out.write("          <input class=\"layui-input\" autocomplete=\"off\" placeholder=\"搜索内容，回车跳转\" type=\"text\" name=\"q\">\r\n");
      out.write("        </form>\r\n");
      out.write("        <a href=\"add.html\" class=\"layui-btn jie-add\">发布问题</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <ul class=\"fly-list\" id = \"content\">\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("      <!-- <div class=\"fly-none\">并无相关数据</div> -->\r\n");
      out.write("    \r\n");
      out.write("      <div style=\"text-align: center\">\r\n");
      out.write("        <!-- 分页<div class=\"laypage-main\"><span class=\"laypage-curr\">1</span><a href=\"/jie/page/2/\">2</a><a href=\"/jie/page/3/\">3</a><a href=\"/jie/page/4/\">4</a><a href=\"/jie/page/5/\">5</a><span>…</span><a href=\"/jie/page/148/\" class=\"laypage-last\" title=\"尾页\">尾页</a><a href=\"/jie/page/2/\" class=\"laypage-next\">下一页</a></div> -->\r\n");
      out.write("      \t<div id=\"pagebar\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type = \"text/html\" id = \"item\">\r\n");
      out.write("{{each list as value}}\r\n");
      out.write("<li class=\"fly-list-li\">\r\n");
      out.write("<a href=\"user/home.html\" class=\"fly-list-avatar\">\r\n");
      out.write("  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/upload/{{value.head_url}}\" alt=\"\">\r\n");
      out.write("</a>\r\n");
      out.write("<h2 class=\"fly-tip\">\r\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/topic_detail.do?id={{value.id}}\"> {{value.title}} </a>\r\n");
      out.write("  <span class=\"fly-tip-stick\">置顶</span>\r\n");
      out.write("</h2>\r\n");
      out.write("<p>\r\n");
      out.write("  <span><a href=\"user/home.html\">{{value.nickname}}</a></span>\r\n");
      out.write("  <span>{{value.createtime}}</span>\r\n");
      out.write("  <span>技术闲谈</span>\r\n");
      out.write("  <span class=\"fly-list-hint\"> \r\n");
      out.write("    <i class=\"iconfont\" title=\"回答\">&#xe60c;</i> 502\r\n");
      out.write("    <i class=\"iconfont\" title=\"人气\">&#xe60b;</i> {{value.viewCount}}\r\n");
      out.write("  </span>\r\n");
      out.write("</p>\r\n");
      out.write("</li>\r\n");
      out.write("  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/layui.all.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.use('laypage', function(){\r\n");
      out.write("  var laypage = layui.laypage;\r\n");
      out.write("  \r\n");
      out.write("\t//创建ajax对象\r\n");
      out.write("\tvar request = new XMLHttpRequest();\r\n");
      out.write("\t\r\n");
      out.write("\t//与服务器建立连接\r\n");
      out.write("\trequest.open(\"get\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/totalcount.do\",true);\r\n");
      out.write("\t//第一次发送ajax请求，向服务器索要当前表一共有多少条记录\r\n");
      out.write("\trequest.send();\r\n");
      out.write("\t\r\n");
      out.write("\t//监控当前ajax请求状态，绑定事件处理函数\r\n");
      out.write("\trequest.onreadystatechange = function(){\r\n");
      out.write("\t\t//alert(req.readyState);//输出当前ajax请求 所处的状态\r\n");
      out.write("\t\t//已经成功获得服务器回应\r\n");
      out.write("\t\tif(request.readyState===4){\r\n");
      out.write("\t\t\t//服务器响应成功\r\n");
      out.write("\t\t\tif(request.status === 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar totalcount = request.responseText;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//发第二次ajax请求，向服务器索要第一页数据\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//执行一个laypage实例\r\n");
      out.write("\t\t\t\t  laypage.render({\r\n");
      out.write("\t\t\t\t    elem: 'pagebar', //注意，这里的 test1 是 ID，不用加 # 号\r\n");
      out.write("\t\t\t\t    limit:3,\r\n");
      out.write("\t\t\t\t    count:totalcount, //数据总数，从服务端得到\r\n");
      out.write("\t\t\t\t    jump: function(obj, first){\r\n");
      out.write("\t\t\t\t        //obj包含了当前分页的所有参数，比如：\r\n");
      out.write("\t\t\t\t        console.log(obj.curr); //得到当前页，以便向服务端请求对应页的数据。\r\n");
      out.write("\t\t\t\t        console.log(obj.limit); //得到每页显示的条数\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t      //创建ajax对象\r\n");
      out.write("\t\t\t\t\t\tvar req = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//与服务器建立连接\r\n");
      out.write("\t\t\t\t\t\treq.open(\"get\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/page.do?pageIndex=\"+obj.curr+\"&pageSize=\"+obj.limit,true);\r\n");
      out.write("\t\t\t\t\t\t//发送请求\r\n");
      out.write("\t\t\t\t\t\treq.send();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//监控当前ajax请求状态，绑定事件处理函数\r\n");
      out.write("\t\t\t\t\t\treq.onreadystatechange = function(){\r\n");
      out.write("\t\t\t\t\t\t\t//alert(req.readyState);//输出当前ajax请求 所处的状态\r\n");
      out.write("\t\t\t\t\t\t\t//已经成功获得服务器回应\r\n");
      out.write("\t\t\t\t\t\t\tif(req.readyState===4){\r\n");
      out.write("\t\t\t\t\t\t\t\t//服务器响应成功\r\n");
      out.write("\t\t\t\t\t\t\t\tif(req.status === 200)\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar ul = document.getElementById(\"content\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(req.responseText);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar jsonObj = JSON.parse(req.responseText);//json字符串转成json对象\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar html = template('item',jsonObj);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t\t\t\tul.innerHTML = html;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\telse//响应失败\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        //首次不执行\r\n");
      out.write("\t\t\t\t        if(!first){\r\n");
      out.write("\t\t\t\t          //do something\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse//响应失败\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'jie';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
