/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2017-11-02 05:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fset_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>帐号设置</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/css/global.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"/\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"index.html\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-user\">      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      \r\n");
      out.write("      <a class=\"avatar\" href=\"../user/index.html\">\r\n");
      out.write("        <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\">\r\n");
      out.write("        <cite>贤心</cite>\r\n");
      out.write("        <i>VIP2</i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"nav\">\r\n");
      out.write("        <a href=\"../user/set.html\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
      out.write("        <a href=\"\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main fly-user-main layui-clear\">\r\n");
      out.write("  <ul class=\"layui-nav layui-nav-tree layui-inline\" lay-filter=\"user\">\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"home.html\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe609;</i>\r\n");
      out.write("        我的主页\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"index.html\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe612;</i>\r\n");
      out.write("        用户中心\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item layui-this\">\r\n");
      out.write("      <a href=\"set.html\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe620;</i>\r\n");
      out.write("        基本设置\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"message.html\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe611;</i>\r\n");
      out.write("        我的消息\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"site-tree-mobile layui-hide\">\r\n");
      out.write("    <i class=\"layui-icon\">&#xe602;</i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"site-mobile-shade\"></div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"fly-panel fly-panel-user\" pad20>\r\n");
      out.write("    <div class=\"layui-tab layui-tab-brief\" lay-filter=\"user\">\r\n");
      out.write("      <ul class=\"layui-tab-title\" id=\"LAY_mine\">\r\n");
      out.write("        <li class=\"layui-this\" lay-id=\"info\">头像</li>\r\n");
      out.write("        <li lay-id=\"avatar\">我的资料</li>\r\n");
      out.write("        <li lay-id=\"pass\">密码</li>\r\n");
      out.write("     <!--    <li lay-id=\"bind\">帐号绑定</li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div class=\"layui-tab-content\" style=\"padding: 20px 0;\">\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"layui-form layui-form-pane layui-tab-item\">\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <div class=\"avatar-add\">\r\n");
      out.write("                <p>建议尺寸168*168，支持jpg、png、gif，最大不能超过30KB</p>\r\n");
      out.write("                <div class=\"upload-img5\">\r\n");
      out.write("                <form action=\"/user/repass\" method=\"post\">\r\n");
      out.write("                  <input type=\"file\" name=\"file\" id=\"LAY-file\" lay-title=\"上传头像\">\r\n");
      out.write("                   <input type=\"submit\" class=\"layui-btn\" lay-filter=\"*\" value=\"立即上传\"></input>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img src=\"http://tp4.sinaimg.cn/1345566427/180/5730976522/0\">\r\n");
      out.write("                <span class=\"loading\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        <div class=\"layui-form layui-form-pane layui-tab-item layui-show\">\r\n");
      out.write("          <form method=\"post\" action=\"/vv.do\">\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_email\" class=\"layui-form-label\">邮箱</label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                <input type=\"text\" id=\"L_email\" name=\"email\" required lay-verify=\"email\" autocomplete=\"off\" value=\"\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"layui-form-mid layui-word-aux\">如果您在邮箱已激活的情况下，变更了邮箱，需<a href=\"activate.html\" style=\"font-size: 12px; color: #4f99cf;\">重新验证邮箱</a>。</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_username\" class=\"layui-form-label\">昵称</label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                <input type=\"text\" id=\"L_username\" name=\"username\" required lay-verify=\"required\" autocomplete=\"off\" value=\"\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"layui-inline\">\r\n");
      out.write("                <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"radio\" name=\"sex\" value=\"0\" checked title=\"男\">\r\n");
      out.write("                  <input type=\"radio\" name=\"sex\" value=\"1\" title=\"女\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_city\" class=\"layui-form-label\">城市</label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                <input type=\"text\" id=\"L_city\" name=\"city\" autocomplete=\"off\" value=\"\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item layui-form-text\">\r\n");
      out.write("              <label for=\"L_sign\" class=\"layui-form-label\">签名</label>\r\n");
      out.write("              <div class=\"layui-input-block\">\r\n");
      out.write("                <textarea placeholder=\"随便写些什么刷下存在感\" id=\"L_sign\"  name=\"sign\" autocomplete=\"off\" class=\"layui-textarea\" style=\"height: 80px;\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"layui-form-item\">\r\n");
      out.write("              <button class=\"layui-btn\" key=\"set-mine\" lay-filter=\"*\" lay-submit>确认修改</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("          <div class=\"layui-form layui-form-pane layui-tab-item\">\r\n");
      out.write("            <form action=\"/zz.do\" method=\"post\">\r\n");
      out.write("              <div class=\"layui-form-item\">\r\n");
      out.write("                <label for=\"L_nowpass\" class=\"layui-form-label\">当前密码</label>\r\n");
      out.write("                <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_nowpass\" name=\"nowpass\" required lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"layui-form-item\">\r\n");
      out.write("                <label for=\"L_pass\" class=\"layui-form-label\">新密码</label>\r\n");
      out.write("                <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_pass\" name=\"pass\" required lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"layui-form-mid layui-word-aux\">6到16个字符</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"layui-form-item\">\r\n");
      out.write("                <label for=\"L_repass\" class=\"layui-form-label\">确认密码</label>\r\n");
      out.write("                <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_repass\" name=\"repass\" required lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"layui-form-item\">\r\n");
      out.write("                 <input type=\"submit\" class=\"layui-btn\" lay-filter=\"*\" value=\"立即上传\"></input>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!--  <div class=\"layui-form layui-form-pane layui-tab-item\">\r\n");
      out.write("            <ul class=\"app-bind\">\r\n");
      out.write("              <li class=\"fly-msg app-havebind\">\r\n");
      out.write("                <i class=\"iconfont icon-qq\"></i>\r\n");
      out.write("                <span>已成功绑定，您可以使用QQ帐号直接登录Fly社区，当然，您也可以</span>\r\n");
      out.write("                <a href=\"javascript:;\" class=\"acc-unbind\" type=\"qq_id\">解除绑定</a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"\" onclick=\"layer.msg('正在绑定微博QQ', {icon:16, shade: 0.1, time:0})\" class=\"acc-bind\" type=\"qq_id\">立即绑定</a>\r\n");
      out.write("                <span>，即可使用QQ帐号登录Fly社区</span>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"fly-msg\">\r\n");
      out.write("                <i class=\"iconfont icon-weibo\"></i>\r\n");
      out.write("                <span>已成功绑定，您可以使用微博直接登录Fly社区，当然，您也可以</span>\r\n");
      out.write("                <a href=\"javascript:;\" class=\"acc-unbind\" type=\"weibo_id\">解除绑定</a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"\" class=\"acc-weibo\" type=\"weibo_id\"  onclick=\"layer.msg('正在绑定微博', {icon:16, shade: 0.1, time:0})\" >立即绑定</a>\r\n");
      out.write("                <span>，即可使用微博帐号登录Fly社区</span>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div> -->\r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'user';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
